# Generated by Django 5.1.7 on 2025-03-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caaordserv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('nao_iniciada', 'Não Iniciada'), ('em_andamento', 'Em Andamento'), ('aguardando_parecer', 'Aguardando Parecer'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='nao_iniciada', max_length=20),
        ),
    ]
