# Generated by Django 5.1.7 on 2025-03-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caaordserv', '0002_ordemservico_deleted_at_alter_ordemservico_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='justificativa_cancelamento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
