# Generated by Django 5.1.7 on 2025-03-29 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caaordserv', '0003_remove_ordemservico_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoOrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='ordens_servico/anexos/%Y/%m/%d/')),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('foto', 'Foto'), ('documento', 'Documento'), ('outro', 'Outro')], max_length=50)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='caaordserv.ordemservico')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
                'ordering': ['-data_upload'],
            },
        ),
    ]
