# Generated by Django 5.1.7 on 2025-03-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caaordserv', '0004_anexoordemservico'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='parecer',
            field=models.TextField(blank=True, help_text='Parecer técnico para finalização da ordem de serviço', null=True),
        ),
    ]
