# Generated by Django 5.2.6 on 2025-09-30 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caaordserv', '0005_update_processo_format_6digits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordemservico',
            options={'ordering': ['-processo'], 'verbose_name': 'Ordem de Serviço', 'verbose_name_plural': 'Ordens de Serviço'},
        ),
    ]
