# Generated by Django 5.2.6 on 2025-11-15 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTwoFactorAuth',
        ),
    ]
