# Generated by Django 5.1.7 on 2025-03-29 12:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processo', models.CharField(editable=False, max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('atendimento_veterinario', 'Atendimento Veterinário'), ('denuncia_maus_tratos', 'Denúncia de Maus Tratos'), ('castracao', 'Castração'), ('captura_grande_porte', 'Captura de Animais de Grande Porte')], max_length=50)),
                ('nome_solicitante', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.TextField()),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('nao_iniciada', 'Não Iniciada'), ('em_andamento', 'Em Andamento'), ('aguardando_parecer', 'Aguardando Parecer'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='aguardando_parecer', max_length=20)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
